---
title: "Stepwise Forward Selection"
author: "Christian Pascual"
date: "2/10/2019"
output: html_document
---

```{r libraries, message = FALSE}
library(tidyverse)
library(MASS)
library(matrixcalc)
library(glmnet)
```

# Multiple simulations

```{r simulation-functions }
simulate.data = function(n = 100, 
                         c = 1, cor.base = 0.30, strong.coeff = 5,
                         num.strong = 5, num.wai = 10, num.wbc = 10, num.p = 100) {
  
  num.null = num.p - (num.strong + num.wai + num.wbc)
  weak.threshold = c * sqrt(log(num.p) / n)
  var.matrix = diag(num.p)
  
  # ensure covariates are correlated to the first strong covariate
  var.matrix[1, (num.strong + num.wai + 1):(num.strong + num.wai + num.wbc)] = cor.base
  var.matrix[(num.strong + num.wai + 1):(num.strong + num.wai + num.wbc), 1] = cor.base
  
  if (!is.positive.definite(var.matrix)) {
    return("Given parameters do not form positive definite variance-covariance matrix.")
  }
  
  # simulate the data from multivariate normal
  X = mvrnorm(n = n, mu = rep(0, num.p), Sigma = var.matrix, empirical = F, tol = 0.1)
  
  b.true = c(
    rep(strong.coeff, num.strong),
    rep(weak.threshold, num.wai), 
    rep(weak.threshold, num.wbc),
    rep(0, num.null) 
  )
  
  Y = 1 + X %*% b.true + rnorm(n)
  data = as.tibble(data.frame(cbind(X, Y)))
  
  # clearly demarcate columns
  cols = c(
    paste("Strong", 1:num.strong, sep = ""),
    paste("WAI", 1:num.wai, sep = ""),
    paste("WBC", 1:num.wbc, sep = ""),
    paste("Null", 1:num.null, sep = ""),
    "Y"
  )
  colnames(data) = cols
  return(data)
}

create.forward.model = function(data) {
  null = formula(lm(Y ~ 1, data = data))
  full = formula(lm(Y ~ ., data = data))
  
  fit = step(object = lm(Y ~ 1, data = data),
             scope = list(lower = null, upper = full), 
             direction = "forward", trace = 0)
  
  return(fit)
}

extract.lasso.params = function(data) {
  
  # Grab the last parameter name since Y is the last column of the data
  last.param.name = names(data[, ncol(data) - 1])
  
  # Convert the tibble data into matrices for LASSO
  X = data %>% dplyr::select(., Strong1:last.param.name) %>% as.matrix(.)
  Y = data %>% dplyr::select(., Y) %>% as.matrix(.)
  fit.lasso = cv.glmnet(X, Y, nfolds = 10, type.measure = "mse")
  
  param.best = fit.lasso$glmnet.fit$beta[, fit.lasso$lambda == fit.lasso$lambda.1se] 
  
  # capture non-zero params
  non.zeroes = param.best[param.best != 0]

  return(non.zeroes)
}

```

```{r helper-functions }
# Functions to help with gathering simulation data

# task 1: gather how many predictors were missed by forward selection/LASSO
analyze.missed = function(betas, num.p, model,
                          num.strong = 5, num.wai = 10, num.wbc = 10) {
  strongs = paste("Strong", 1:num.strong, sep = "")
  wais = paste("WAI", 1:num.wai, sep = "")
  wbcs = paste("WBC", 1:num.wbc, sep = "")
  captured = names(betas)

  return(list(
    model = model,
    num.p = num.p,
    num.betas = length(betas),
    prct.strong = length(intersect(captured, strongs)) / length(strongs),
    prct.wai = length(intersect(captured, wais)) / length(wais),
    prct.wbc = length(intersect(captured, wbcs)) / length(wbcs)
  ))
}

# task 2 subtask: remove weak predictors from the data before fitting model to it
remove.weaknesses = function(data, rm.wai = 0, rm.wbc = 0) {
  # definte which columns we should remove from WBC and WAI
  cols.to.remove = c(
    paste("WAI", 1:rm.wai, sep = ""),
    paste("WBC", 1:rm.wbc, sep = "")
  )

  return(data[, !(names(data) %in% cols.to.remove)])
}
```

```{r scenario-parameters-task-1 }
n = 100
c.vals = c(1, 2, 3)
cor.base = 0.30
strong.coeff = 5
num.strong = 5
num.wai = 10
num.wbc = 10
num.p = c(30, 40, 50, 60, 70, 80, 90)
num.sims = 100
```

```{r task-1 }
set.seed(8160)
task.1.simulations = NULL

for (c in 1:length(c.vals)) {
  for (i in 1:length(num.p)) {
    for (j in 1:num.sims) {
      
      # simulate the dataset with above parameters
      data = simulate.data(n = n, c = c, cor.base = cor.base,
                           strong.coeff = strong.coeff, 
                           num.strong = num.strong, num.wai = num.wai, 
                           num.wbc = num.wbc, 
                           num.p = num.p[i])
      
      # create the forward model
      forward.model = create.forward.model(data)
      
      # create the LASSO model and extract parameters
      lasso.parameters = extract.lasso.params(data)
      
      # calculate the percentages of coefficients missed
      forward.selection.data = analyze.missed(forward.model$coefficients, 
                                              num.p = num.p[i],
                                              model = "Stepwise")
      lasso.data = analyze.missed(lasso.parameters, 
                                  num.p = num.p[i],
                                  model = "LASSO")
      
      # Gather created models for diagnostics
      task.1.simulations = bind_rows(task.1.simulations, forward.selection.data)
      task.1.simulations = bind_rows(task.1.simulations, lasso.data)
      
      print(paste("Simulation", j, "of", "p =", num.p[i], "c =", c, "done!"))
    }
  }
}
```

```{r task-1-visualization }
task.1.simulations = task.1.simulations %>% 
  mutate(num.p = as.character(num.p))

c.vals = c(rep(1, 700), rep(2, 700), rep(3, 700))

test = task.1.simulations %>% 
  mutate(c = c.vals)

ggplot(data = test, aes(x = prct.wai, fill = num.p, color = num.p)) +
  geom_density(alpha = 0.1)
```

```{r saving-sim-data-1 }
write.csv(test, "task-1-simulation.csv")
```

# Task 2

```{r scenario-parameters-task-2 }
n = 100
c.vals = 1
cor.base = 0.30
strong.coeff = 5
num.strong = 5
num.wai = 10
num.wbc = 10
num.p = 50
num.sims = 1
```

```{r task-2 }
set.seed(8161)
task.2.simulations = NULL
count = 0

# Remove WAI and WBC one at a time in alternating fashion
for (k in 0:num.wbc) {
  for (i in 0:num.wai) {
    for (j in 1:num.sims) {
      
      # simulate the dataset with above parameters
      data = simulate.data(n = n, c = c, cor.base = cor.base,
                           strong.coeff = strong.coeff, 
                           num.strong = num.strong, num.wai = num.wai, 
                           num.wbc = num.wbc, 
                           num.p = num.p)
      
      # remove weak predictors from the data
      weakened.data = remove.weaknesses(data, rm.wai = i, rm.wbc = k)
      
      # create the forward model
      forward.model = create.forward.model(weakened.data)
      
      # create LASSO model and get parameters
      lasso.params = extract.lasso.params(weakened.data)
      
      # Gather coefficients from estimated model that did not see some weak predictors
      task.2.simulations = bind_rows(task.2.simulations, 
                                     c(forward.model$coefficients, list("n.weak.missing" = i + k, 
                                                                        "Model" = "Stepwise"))
      )
      task.2.simulations = bind_rows(task.2.simulations, 
                                     c(lasso.params, list("n.weak.missing" = i + k,
                                                                        "Model" = "LASSO"))
      )
      count = count + 1 
      
      print(paste("Simulation", count, "with", k, "WBC removed and", i, "WAI removed done!"))
    }
  }
}

# sanitize all the resulting simulation data 
cleaned.task.2.simulations = task.2.simulations %>% 
  dplyr::select(-starts_with("Null"), -contains("Intercept"))
```

```{r}
# NEED TO PROCESS AND VISUALIZE THE SIMULATION TASK 2 DATA
```

```{r lasso-test }
data  = simulate.data()
lasso.params = extract.lasso.params(data)
test = analyze.missed(lasso.params, num.p = 100, model = "LASSO")
test2 = bind_rows(lasso.params, lasso.params)
```



