---
title: "Visualization Plots"
author: "Angel Garcia de la Garza"
date: "2/15/2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```



```{r}


# Summarizes data, handling within-subjects variables by removing inter-subject variability.
## It will still work if there are no within-S variables.
## Gives count, un-normed mean, normed mean (with same between-group mean),
##   standard deviation, standard error of the mean, and confidence interval.
## If there are within-subject variables, calculate adjusted values using method from Morey (2008).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   withinvars: a vector containing names of columns that are within-subjects variables
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message("Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", "))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, "_norm", sep="")

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  merge(datac, ndatac)
}

```




# Part 1: Histogram

```{r}

data1 <- read_csv("task-1-simulation.csv") %>%
          filter(num.p == "60")


data1 %>%
  ggplot(aes(x=model, y=prct.wai, fill=model)) + 
  geom_boxplot() +
  facet_grid(. ~ c) +
  theme_bw()


data1 %>%
  ggplot(aes(x=model, y=prct.wbc, fill=model)) + 
  geom_boxplot() +
  facet_grid(. ~ c) +
  theme_bw()

```


# Part 1: Violin Plots

```{r}

data1 <- read_csv("task-1-simulation.csv") %>%
          filter(num.p == "60")


data1 %>%
  ggplot(aes(x=model, y=prct.wai, fill=model)) + 
  geom_violin() +
  geom_boxplot(width=0.2, fill = "white")+
  facet_grid(. ~ c) +
  theme_bw() +
  labs(
    title = "Distribution of percent WAI predictors captured in as function of c"
  )


data1 %>%
  ggplot(aes(x=model, y=prct.wbc, fill=model)) + 
  geom_violin() +
  geom_boxplot(width=0.2, fill = "white")+
  facet_grid(. ~ c) +
  theme_bw() +
  labs(
    title = "Distribution of percent WBC predictors captured in as function of c"
  )

```


## Part 2:

# Part 2: Missing Independent Covariates 

```{r}
data2 <- read_csv("task-2-simulation.csv") %>%
            group_by(Model, n.wai.missing) %>%
            summarize(Bias.Strong.1 = mean((Strong1 - 5)^2))
data2 %>%
  ggplot(aes(color=Model, y= Bias.Strong.1, x = n.wai.missing)) + 
  geom_smooth(method = 'gam', formula = y ~ s(x, k = 5)) + 
  geom_point() + 
  theme_bw() 
data2 <- read_csv("task-2-simulation.csv") %>%
            group_by(Model, n.wai.missing) %>%
            summarize(Bias.Strong.2 = mean((Strong2 - 5)^2))
data2 %>%
  ggplot(aes(color=Model, y= Bias.Strong.2, x = n.wai.missing)) + 
  geom_smooth(method = 'gam', formula = y ~ s(x, k = 5)) + 
  geom_point() + 
  theme_bw() + ylim(0,0.5)
```


# Part 2: Missing Dependent Covariates 

```{r}
data2 <- read_csv("task-2-simulation.csv") %>%
            group_by(Model, n.wbc.missing) %>%
            summarize(Bias.Strong.1 = mean((Strong1 - 5)^2))
data2 %>%
  ggplot(aes(color=Model, y= Bias.Strong.1, x = n.wbc.missing)) + 
  geom_smooth(method = 'gam', formula = y ~ s(x, k = 5)) + 
  geom_point() + 
  theme_bw()
data2 <- read_csv("task-2-simulation.csv") %>%
            group_by(Model, n.wbc.missing) %>%
            summarize(Bias.Strong.2 = mean((Strong2 - 5)^2))
data2 %>%
  ggplot(aes(color=Model, y= Bias.Strong.2, x = n.wbc.missing)) + 
  geom_smooth(method = 'gam', formula = y ~ s(x, k = 5)) + 
  geom_point() + 
  theme_bw() + ylim(0,0.5)
```